### ISSUE TITLE
Essai d'import de l'EDT dans le CT à Victor Grignard : pas de créneaux créés

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#215]
Maintenant que tu as résolu le souci des classes  de l'annuaire qui n'apparaissaient pas pour faire le recollement des classes, il n'a pas la main pour reclasser car tout semble être reconnu et le site informe Mr Teysseyre que 40 enseignants ont été reconnus, 20 classes crées et aucun non prises en comptes, et idem pour les groupes d'élèves alors qu'il a plus de groupes d'élèves. 

Autre souci : les créneaux ne sont pas créés après l'essai d'import.

**Comment by cycojesus** [comment]
#todo: toujours remplir rapport[...][errors] si id_annuaire est nil

**Comment by cycojesus** [comment]
Fixed, à tester.
