### ISSUE TITLE
Impossible d'ajouter un créneau quand le serveur de docs n'est pas dispo ou dégradé

### ISSUE THREAD

**Issue by leucos** [laclasse-com/service-cahiertextes#217]
Lorsque l'on essaye de créer un créneau (juste en cliquant dans le CT) et que le serveur de documents est :
- hors service
- dégradé (heure desynchro)

le CT renvoie un 401:

`POST https://v3.laclasse.com/ct/api/v1/creneaux_emploi_du_temps?heure_debut=2015…6T11:00:00.000Z&jour_de_la_semaine=5&matiere_id=&regroupement_id=undefined 401 (Unauthorized)`

Il faudrait que le CT gère cette situation avec plus de grâce:

- l'ajout d'un créneau devrait quand même être possible
- si l'ajout d'un document n'est pas possible, petit message à l'utilisateur
- si l'ajout d'un document n'est pas possible, petit log

D'une manière générale, ça serait bien que les applications puissent se survivre les unes aux autres (exception faite, bien sur, de l'annuaire).

**Comment by cycojesus** [comment]
non reproduit
