### ISSUE TITLE
décallage de deux heures en moins sur nexus 10 chrome en affichage

### ISSUE THREAD

**Issue by Bruno-o** [laclasse-com/service-cahiertextes#225]
je selectionne un créneau de 12h a 13h. je valide je raffraichi (cela devrait se faire automatiquement lors de la validation cela plus logique mais bon...), et sur la tablette il m'affiche mon creneau choisi de 10h a 11h je recommence avec un creneau de 13 a 14h et il m'affiche de 11 a 12h soit a chaque fois 2h de decallage

**Comment by cycojesus** [comment]
vérifier la conf du fuseau horaire de la tablette
