### ISSUE TITLE
Vue liste des devoirs élèves

### ISSUE THREAD

**Issue by yamartin** [laclasse-com/service-cahiertextes#232]
Avec le compte Erasme, élève. 
Quand on va sur le cahier de texte et que l'on clique sur  liste des devoirs, le chargement commence puis reste bloqué et bloque le navigateur (Chrome sur Mac). 

https://v3.laclasse.com/portail/#/app/external?app=CTXT

**Comment by cycojesus** [comment]
Cause : trop de devoirs tuent les devoirs !

**Comment by cycojesus** [comment]
fixed
