### ISSUE TITLE
Archivage des cahiers de textes de fin d'année par classe / toutes matières

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#245]
Rendre possible l'archivage par un profil admin/ direction des cahiers de textes, soit en 1 clic on archives tous les CT de l'année de toutes les classes de l'établissement, soit on fit classe par classe mais avec toutes les matières à la fois, pour réduire le nombre de procédures pour faire cet archivage.

**Comment by cycojesus** [comment]
remplacé par #290
