### ISSUE TITLE
Test V3 - 2016 : [Enseignant]  graphique Statistiques

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#254]
il semble que le graphique en camembert montre les activités saisies non visées et les activités visées … or lorsqu’on clique sur le bouton « saisies » ou « visas » l’affichage est étrange – nous sommes censés avoir juste les activités saisies (au nombre de 5) et on voit quant même une activité « visée » http://screencast.com/t/3EYcstfgFpK

**Comment by cycojesus** [comment]
bug d'(angular-nvd3|nvd3|d3)
