### ISSUE TITLE
Test V3 - 2016 : [Enseignant]  modification travail à faire

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#258]
création d’un « travail à faire le jour même » (du coup le devoir apparait dans « Travail à faire suite à cette séquence pédagogique » et dans l’onglet « Travail à faire pour ce jour »  - la modification d’un élément depuis l’onglet « Travail à faire pour ce jour » n’a pas l’air d’être prise en compte alors que si on modifie un élément depuis l’encart « Travail à faire suite à cette séquence pédagogique » celui-ci est pris en compte.
http://screencast.com/t/P6R9zuT5ZV

**Comment by TestsCGI** [comment]
impossible de modifier l'onglet "travail à faire" lorsque la modification est faite non pas à partir du créneau depuis lequel le TAF a été créé mais à partir d'un créneau ultérieur. Ex. le 31/08 ajout d'un devoir pour le 2/09, lorsqu'on est positionné sur le créneau du 2/09, il n'est pas possible de modifier l'onglet TAF. Le bouton Valider ne répond pas. Corrigé. A retester une fois livré en PROD.

**Comment by cycojesus** [comment]
corrigé en prod

**Comment by TestsCGI** [comment]
test OK
