### ISSUE TITLE
Test V3 - 2016 : [Enseignant]  Ajout ressource

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#261]
comment ajouter une ressource externe ? il y a le bouton Parcourir mais je n’arrive pas à ajouter mon image récupérée depuis mon disque local …  

http://screencast.com/t/VYcEhQelyK4

**Comment by cycojesus** [comment]
fonctionne seulement quand angular est en mode debug

**Comment by TestsCGI** [comment]
Testé OK
