### ISSUE TITLE
Test V3 - 2016 : [Enseignant]  créneau avec plusieurs types de devoir

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#263]
Un créneau sur lequel différents types de devoir a été créé. Celui-ci apparait toujours en bleu (pour devoir à la maison).
Quelle est la règle ?

**Comment by cycojesus** [comment]
DS > DM > fait > à faire

**Comment by TestsCGI** [comment]
Test OK
