### ISSUE TITLE
Test V3 - 2016 : [Eleve] Détails devoir à faire

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#267]
Lors du clic sur le bouton Détails le résultat suivant est obtenu : http://screencast.com/t/mJWTk3jW
Peut-on valider un devoir depuis cet écran ?
Impossible de naviguer dans la fenêtre ou de cliquer sur le bouton Fermer.
Obligé de revenir sur l'accueil pour pouvoir poursuivre sur le cahier de textes.

**Comment by cycojesus** [comment]
non reproduit

**Comment by TestsCGI** [comment]
Ok non reproduit
