### ISSUE TITLE
Test V3 - 2016 : [Personnel de direction] Regroupements affichés par défaut

### ISSUE THREAD

**Issue by TestsCGI** [laclasse-com/service-cahiertextes#270]
Quelle est la règle pour l'affichage des regroupements à l'ouverture de l'écran en fonction des différents modules ?
Validation des saisies par enseignant (il semble que cela soit toutes les classes et groupes de l'établissement) http://screencast.com/t/Jr9zynKbF
Tableaux de bord par classe : http://screencast.com/t/SFxoCmvs3y (quelle est la règle ?)
Emplois du temps : http://screencast.com/t/HXQE1QkQ4 (idem ?)

**Comment by cycojesus** [comment]
Règles de filtrage par défaut :

- Validation des saisies par enseignant: toutes les classes et tous les groupes
- Tableaux de bord par classe : toutes les classes uniquement
- Emplois du temps : la première classe

**Comment by TestsCGI** [comment]
Sur l'onglet Validation des saisies par enseignant, ce sont bien les classes et les groupes qui sont listés mais pas de filtre sur l'établissement.
Corrigé. A retester une fois livré en PROD.

**Comment by cycojesus** [comment]
corrigé en prod

**Comment by TestsCGI** [comment]
Test OK
