### ISSUE TITLE
V4 - quelques détails à corriger sur l'onglet CT de l'outil CT

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#302]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1172343/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by gwenhael-le-moine** [comment]
restauration de la granularité par mois
