### ISSUE TITLE
V4 - corrections à faire pour l'onglet statistiques (profil enseignant)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#303]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1172465/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by gwenhael-le-moine** [comment]
non reproduit...
