### ISSUE TITLE
V4-petites modifications au niveau de l'affichage des fenêtres de l'emploi du temps (élève)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#304]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1173162/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by gwenhael-le-moine** [comment]
affichage de la classe supprimé

**Comment by heleroy** [comment]
ok !
