### ISSUE TITLE
V4 - pas de popup opour voir le detail d'un devoir sur vue "liste des devoirs" (eleve)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#305]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1173335/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by gwenhael-le-moine** [comment]
pas de popup car tout est affiché sur la page
