### ISSUE TITLE
V4 - remarques suite au test de validation des saisies (profil principal)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#306]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1173443/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by CharlotteRizzo** [comment]
Avec un profil principal, l'affichage des saisies en choisissant 1 seule classe ne fonctionne pas. 
Lorsqu'un enseignant ajoute un créneau, il ne se met pas à jour dans le tableau de bord des créneau à valider.

**Comment by CharlotteRizzo** [comment]
De même la case à cocher afficher les saisies ne fonctionne pas

**Comment by CharlotteRizzo** [comment]
le bouton préférence pourrait être enlevé en bas de page
