### ISSUE TITLE
V4 - remarques suite au test de la vue "emploi du temps" (profil principal)

### ISSUE THREAD

**Issue by heleroy** [laclasse-com/service-cahiertextes#308]
[https___portail.grandlyon.fr_lib_execute_,DanaInfo=.atfuwpntrHp1lzqzB44Ry.+execPrint.pdf](https://github.com/laclasse-com/service-cahiertextes/files/1175950/https___portail.grandlyon.fr_lib_execute_.DanaInfo.atfuwpntrHp1lzqzB44Ry.execPrint.pdf)

**Comment by gwenhael-le-moine** [comment]
fixed

**Comment by heleroy** [comment]
Par contre du coup je viens de tester la possibilité pour le principal de déplacer ou modifier un créneau et ça ne fonctionne pas. Le clic ou cliqué-glissé sur le créneau n'a aucun effet excepté pour visualisé une séquence pédagogique ou un devoir saisi.

**Comment by gwenhael-le-moine** [comment]
effectivement ça n'est plus actif que pour les profs... je regarde

**Comment by gwenhael-le-moine** [comment]
corrigé
