### ISSUE TITLE
v4 : profil Parent - Liste des devoirs

### ISSUE THREAD

**Issue by HuguesGithub** [laclasse-com/service-cahiertextes#318]
Lorsque je clique sur le bouton "Liste des devoirs", j'ai un message affichant "Aucun devoir trouvé pour cette période", pourtant, le navigateur semble continuer à mouliner.

La période interrogée est entre le 22 août et le 19 septembre 2017.
L'id est : VCF60114 (celui de mon fils).

J'ai eu des devoirs qui ont fini par s'afficher. Certaines dataient du 11 mai (je ne saurais préciser l'année).

https://www.laclasse.com/ct/api/devoirs?debut=2017-08-22T08:45:03.707Z&fin=2017-09-19T08:45:03.707Z&uid=VCF60114

curl 'https://www.laclasse.com/ct/api/devoirs?debut=2017-08-22T08:45:03.707Z&fin=2017-09-19T08:45:03.707Z&uid=VCF60114' -H 'Accept: application/json, text/plain, */*' -H 'Referer: https://www.laclasse.com/ct/' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36' --compressed

Queued at 7.86 ms
--
Started at 8.12 ms
Resource Scheduling |   | TIME
Queueing | ​ | 0.26 ms
Connection Start |   | TIME
Stalled | ​ | 0.59 ms
Request/Response |   | TIME
Request sent | ​ | 96 μs
Waiting (TTFB) | ​ | 12.24 s
Content Download | ​ | 200.69 ms
CAUTION: request is not finished yet!

**Comment by gwenhael-le-moine** [comment]
réparé
