### ISSUE TITLE
(bug) video youtube non lisible pour les élèves

### ISSUE THREAD

**Issue by CharlotteRizzo** [laclasse-com/service-cahiertextes#323]
Lorsqu'un enseignant ajoute une video dans une séquence pédagogique, cette dernière n'est pas visible pour les élèves. 

test avec elevebas 6em1

**Comment by gwenhael-le-moine** [comment]
done.

**Comment by CharlotteRizzo** [comment]
Merci!!
le lecteur ne fonctionne pas non plus pour les enseignants
